# Site settings
title: "Yogi Tri Cahyono"
description: Data Analytics
email: yogitricahyono@gmail.com

# Build settings
theme: minima
plugins:
  - jekyll-seo-tag

# Minima theme settings
minima:
  skin: classic
  
# Social links (optional - delete any you don't use)
github_username: ygcahyono
linkedin_username: yogitricahyono

# Show only specific pages in navigation (posts will be automatically excluded)
header_pages:
  - index.md
  - datascience.md
