# Site settings
title: Yogi Tri Cahyono
description: Data Scientist at TikTok Shop South East Asia
email: yogitricahyono@gmail.com

# Build settings
theme: minima
plugins:
  - jekyll-seo-tag

# Minima theme settings
minima:
  skin: classic
  
# Social links (optional - delete any you don't use)
github_username: ygcahyono
linkedin_username: yogitricahyono

# Hide the default header and footer for a cleaner look
header_pages: []
